/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        './pages/**/*.{js,jsx}',
        './components/**/*.{js,jsx}',
        './app/**/*.{js,jsx}',
        './src/**/*.{js,jsx}',
    ],
    prefix: "",
    theme: {
        fontFamily: {
            dax: ['DAX', 'sans-serif'], // Add your custom font here
        },
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "xs": "270",
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                // primary: {
                //     DEFAULT: "hsl(var(--primary))",
                //     foreground: "hsl(var(--primary-foreground))",
                // },
                // secondary: {
                //     DEFAULT: "hsl(var(--secondary))",
                //     foreground: "hsl(var(--secondary-foreground))",
                // },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                primary: {
                    50: '#fcf6f0',
                    100: '#f9e8db',
                    200: '#f1cfb7',
                    300: '#e8ae89',
                    400: '#de8559',
                    500: '#d76a3e',
                    600: '#C94D25',
                    700: '#a63e28',
                    800: '#853327',
                    900: '#6c2c22',
                    950: '#3a1410',
                },
                secondary: {
                    50: '#f5f6f6',
                    100: '#e6e7e7',
                    200: '#d0d1d1',
                    300: '#aeb2b2',
                    400: '#868a89',
                    500: '#6b6f6e',
                    600: '#5e6262',
                    700: '#4e5050',
                    800: '#444646',
                    900: '#3c3d3d',
                    950: '#252627',
                },
                danger: {
                    50: '#F5F5F1',
                    100: '#E7E5DA',
                    200: '#D1CCB7',
                    300: '#B6AD8E',
                    400: '#A49672',
                    500: '#928260',
                    600: '#7D6C51',
                    700: '#655443',
                    800: '#57483C',
                    900: '#4C3F37',
                },
                success: {
                    50: '#F1FCFA',
                    100: '#CEF9F1',
                    200: '#9DF2E4',
                    300: '#64E4D4',
                    400: '#34CDBE',
                    500: '#1BB1A5',
                    600: '#149991',
                    700: '#13726D',
                    800: '#145B58',
                    900: '#154C4A',
                },
                warning: {
                    50: '#FFF9ED',
                    100: '#FEF2D6',
                    200: '#FDE1AB',
                    300: '#FBCA76',
                    400: '#F8A83F',
                    500: '#F69222',
                    600: '#E7730F',
                    700: '#BF570F',
                    800: '#984514',
                    900: '#7A3A14',
                },
                gold: {
                    50: '#F5F5F1',
                    100: '#E7E5DA',
                    200: '#D1CCB7',
                    300: '#B6AD8E',
                    400: '#A49672',
                    500: '#928260',
                    600: '#7D6C51',
                    700: '#655443',
                    800: '#57483C',
                    900: '#4C3F37',
                },
                blacked: {
                    50: '#F6F6F6',
                    100: '#E7E7E7',
                    200: '#D1D1D1',
                    300: '#B0B0B0',
                    400: '#888888',
                    500: '#6D6D6D',
                    600: '#5D5D5D',
                    700: '#4F4F4F',
                    800: '#454545',
                    900: '#3D3D3D',
                    950: '#000000',
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: {height: "0"},
                    to: {height: "var(--radix-accordion-content-height)"},
                },
                "accordion-up": {
                    from: {height: "var(--radix-accordion-content-height)"},
                    to: {height: "0"},
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
}
